### ISSUE TITLE
"URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>"

### ISSUE THREAD

**Issue by 183amir** [conda-forge/openssl-feedstock#2]
I am getting this error all over the place. Is this related to `openssl`?
```
======================================================================
ERROR: bob.extension.test_extensions.test_project
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/envs/_test/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/opt/conda/envs/_test/lib/python2.7/site-packages/bob/extension/test_extensions.py", line 76, in test_project
    _run('project', ['./bin/version.py'])
  File "/opt/conda/envs/_test/lib/python2.7/site-packages/bob/extension/test_extensions.py", line 37, in _run
    url = urllib.urlopen(example_url)
  File "/opt/conda/envs/_test/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/conda/envs/_test/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/opt/conda/envs/_test/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/opt/conda/envs/_test/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/opt/conda/envs/_test/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/opt/conda/envs/_test/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>
```
full log here: https://circleci.com/gh/conda-forge/bob.extension-feedstock/26

**Comment by 183amir** [comment]
This is being fixed here: https://github.com/conda-forge/ca-certificates-feedstock/pull/4

**Comment by jakirkham** [comment]
Feel free to restart this build.

**Comment by jakirkham** [comment]
To restore to a working version of `ca-certificates` in an existing environment, try this `conda install -c conda-forge ca-certificates=2016.2.28=0`.
